logging:
# specify alternative file location
#  path: /var/logs/
#  file: BookWorm.log
# alternative log config file name
#  config:
#    classpath:logging-config.xml
  level:
    root: WARN
    org.springframework:
      security: INFO
      boot.autoconfigure.security: INFO
#  datasource:
#    url: jdbc:mysql://localhost/readinglist
#    username: dbuser
#    password: dbpass
##    usually, not necessary
#    driver-class-name: com.mysql.jdbc.Driver

# look up the DataSource from JNDI
#spring:
#  datasource:
#    jndi-name: java:/comp/env/jdbc/readingListDS

amazon:
  associateId: habuma-20